### ISSUE TITLE
Fix an Ansible script to install Decidim

### ISSUE THREAD

**Issue by PierreMesure** [digidemlab/decidim-sweden#8]
# TO-DO:

## Server
- [x] Provision a VPS

## External services
- [x] Request a token from Sentry
- [x] Request a token from Matomo
- [ ] Request specific STMP credentials (optional)

## Linux
- [X] `apt-upgrade`
- [X] Set timezone
- [X] Create Linux user

## Database
- [X] Install Postgres
- [X] Install Redis

## Dependencies
- [X] Install Rbenv
- [X] Install Ruby
- [X] Install Bundler
- [X] Install NodeJS
- [X] Install Nginx
- [X] Install Sidekiq

## Decidim 
- [X] Checkout Decidim app from repo
- [X] Install gems
- [X] Install Figaro
- [X] Import env variables with Figaro
- [X] Precompile assets
- [X] Create database for Decidim
- [X] Create table structure for database
- [X] Create Decidim system admin
- [ ] Create organisation with SMTP settings

## Security
- [X] Set up SSL certificate (with Let's encrypt or private key)

## Other
- [X] Install antivirus ClamAV
- [X] Schedule file and DB backups
- [x] Set up Matomo for analytics
